version: '3.8'
networks:
  network:
    driver: bridge

services:
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 0623
      MYSQL_DATABASE: SubwayChat
    networks:
      - network

  redis:
    image: "redis:7.0"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - network

